version: '3'
volumes:
  ## volumeを追加することでlaravelの動作を早くする
  vendor-store:
  node_modules-store:

services:
  php:
    container_name: kousatu_php
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
    - ./:/var/www:cached
    - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - vendor-store:/var/www/vendor

  nginx:
    image: nginx:1.17.10
    container_name: kousatu_nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./:/var/www:cached
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    - node_modules-store:/var/www/node_modules
    depends_on:
    - php
    networks:
      default:
        aliases:
          - kousatu.local

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: db-host
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306

  selenium:
    container_name: chrome
    platform: linux/amd64
    image: selenium/standalone-chrome
    ports:
      - 4444:4444

  db-testing:
    image: mysql:5.7
    platform: linux/amd64
    container_name: db-testing
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_TESTING}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

    tmpfs:
      - /var/lib/mysql
      - /var/log/mysql
    ports:
      - ${DB_PORT_TESTING}:3306
