version: 2
jobs:
    build:
        # machine: true
        docker:
            - image: circleci/php:7.3-stretch-node-browsers
            - image: circleci/mysql:5.7

            # duskテスト用
            - image: circleci/node:7.10-browsers
            - image: selenium/standalone-chrome

        environment:
            - APP_DEBUG: true
            - APP_ENV: testing
            - APP_KEY: base64:XOrH3Y+mrgWbcanrysRacUeB65LqheafmfhJ2bI8nJ4=
            - DB_CONNECTION: circle_testing
            - MYSQL_ALLOW_EMPTY_PASSWORD: true


        steps:
            - run: git config --global core.quotepath false
            
            - checkout
            - setup_remote_docker

            - run:
                name: setup
                command: |
                    sudo apt update && sudo apt install -y mariadb-client libpng-dev libjpeg-dev zlib1g-dev |
                    sudo docker-php-ext-configure gd --with-png-dir=/usr/include --with-jpeg-dir=/usr/include |
                    sudo docker-php-ext-install zip pdo_mysql gd
                    sudo composer self-update
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.lock" }}
                    - composer-v1-
            - run: composer install -n --prefer-dist
            - save_cache:
                key: composer-v1-{{ checksum "composer.lock" }}
                paths:
                    - vendor
            - restore_cache:
                keys:
                    - node-v1-{{ checksum "package-lock.json" }}
                    - node-v1-
            - run: npm install
            - save_cache:
                key: node-v1-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules
            - run: php artisan migrate
            - run: npm run production
            - run: sudo apt install vim
            # - run: ./vendor/bin/phpunit
            # - run: php artisan dusk:chrome-driver
            
            # - run:
            #     name: Start Chrome Driver
            #     command: ./vendor/laravel/dusk/bin/chromedriver-linux
            #     background: true

            - run:
                name: Run Laravel Server
                command: php artisan serve
                background: true

            - run:
                name: run selenium　
                command: docker run -d -p 4444:4444 selenium/standalone-chrome
            - run: 
                name: start browser test
                command: php artisan dusk
                # environment:
                #     APP_URL: http://localhost:8000

            - store_artifacts:
                path: tests/Browser/screenshots/
            # - run:
            #     name: Setup Environment Variable
            #     command: |
            #         cp .env.testing .env
            # - run:
            #     name: Setup docker
            #     command: |
            #         docker-compose up -d --build
            # - restore_cache:
            #     keys:
            #         - composer-v1-{{ checksum "composer.lock" }}
            #         - composer-v1-
            # - run:
            #     name: Install Composer
            #     command: |
            #         docker-compose run php composer install --prefer-dist
            # - save_cache:
            #     key: composer-v1-{{ checksum "composer.lock" }}
            #     paths:
            #         - vendor
            # - run:
            #     name: Setup Laravel
            #     command: |
            #         docker-compose run php chmod -R a+w storage/ bootstrap/cache
            #         docker-compose run php php artisan migrate:refresh --seed
            # - run:
            #     name: Install npm
            #     command: |
            #         docker-compose run php npm install
            #         docker-compose run php npm run prod
            # - save_cache: # special step to save the dependency cache with the `package.json` cache key template
            #     key: node-v1-{{ checksum "package.json" }}
            #     paths:
            #         - node_modules

#     test:
#         machine: true
#         steps:
#             - checkout
#             - run:
#                 name: Run test
#                 command: |
#                     docker-compose run php php artisan dusk
#                     docker-compose run php vendor/bin/phpunit

#     # deplay:
#     #     machine:
#     #         - checkout


# workflows:
#     version: 2
#     build_test_and_deploy:
#         jobs:
#             - build:
#                 context: kousatu
#             - test:  
#                 requires:
#                     - build                  
#                 context: kousatu
#             # - deplay:
#             #     requires:
#             #         - test