version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: Setup Environment Variable
                command: |
                    cp .env.testing .env
            - run:
                name: Setup docker
                command: |
                    docker-compose up -d --build
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.lock" }}
                    - composer-v1-
            - run:
                name: Install Composer
                command: |
                    docker-compose run php composer install --prefer-dist
            - save_cache:
                key: composer-v1-{{ checksum "composer.lock" }}
                paths:
                    - vendor
            - run:
                name: Setup Laravel
                command: |
                    docker-compose run php chmod -R a+w storage/ bootstrap/cache
                    docker-compose run php php artisan migrate:refresh --seed
            - run:
                name: Install npm
                command: |
                    docker-compose run php npm install
                    docker-compose run php npm run prod
            - save_cache: # special step to save the dependency cache with the `package.json` cache key template
                key: node-v1-{{ checksum "package.json" }}
                paths:
                    - node_modules

            - run:
                name: Run test
                command: |
                    docker-compose run php php artisan dusk
                    docker-compose run php vendor/bin/phpunit
workflows:
    version: 2
    build_and_test:
        jobs:
            - build:
                context: kousatu
