version: 2
jobs:
    build:
        context: kousatu
        machine: true
        steps:
            - checkout
            - run:
                name: Setup Environment Variable
                command: |
                    cp .env.testing .env
            - run:
                name: Setup docker
                command: |
                    docker-compose up -d --build
            - run:
                name: Setup Laravel
                command: |
                    docker-compose run php php artisan migrate: refresh --seed
            - run:
                name: Run test
                command: |
                    docker-compose run php vender/bin/phpunit
                    docker-compose run php php artisan dusk